# build stage
FROM registry.fedoraproject.org/fedora:43 AS builder

RUN dnf -y --nodocs --setopt=install_weak_deps=False install \
  git vim make gcc cmake ninja-build lld clang clang-devel compiler-rt \
  libcurl-devel rdma-core-devel vulkan-loader-devel vulkaninfo \
  mesa-vulkan-drivers spirv-headers-devel radeontop glslc patch && \
  dnf clean all && rm -rf /var/cache/dnf/*

WORKDIR /opt/llama.cpp
RUN git clone https://github.com/ggerganov/llama.cpp.git . && \
  git fetch origin pull/27342/head:dflash2-pr && \
  git checkout dflash2-pr && \
  git submodule update --recursive

COPY llama-grammar.patch /tmp/llama-grammar.patch

RUN patch -p1 < /tmp/llama-grammar.patch && \
  cmake -S . -B build -G Ninja \
    -DGGML_VULKAN=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DGGML_RPC=ON \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLLAMA_BUILD_TESTS=OFF \
    -DLLAMA_BUILD_EXAMPLES=ON \
    -DLLAMA_BUILD_SERVER=ON && \
  cmake --build build --config Release -- -j$(nproc) && \
  cmake --install build --config Release

RUN find /opt/llama.cpp/build -type f -name 'lib*.so*' -exec cp {} /usr/lib64/ \; && ldconfig


# runtime stage
FROM registry.fedoraproject.org/fedora-minimal:43

RUN microdnf -y --nodocs --setopt=install_weak_deps=0 install \
  bash ca-certificates libatomic libstdc++ libgcc libibverbs \
  vulkan-loader vulkan-loader-devel vulkaninfo mesa-vulkan-drivers radeontop procps-ng && \
  microdnf clean all && rm -rf /var/cache/dnf/*

COPY --from=builder /usr/ /usr/
COPY --from=builder /usr/local/ /usr/local/
COPY --from=builder /opt/llama.cpp/build/bin/ggml-rpc-* /usr/local/bin/

RUN echo "/usr/local/lib" > /etc/ld.so.conf.d/local.conf && \
  echo "/usr/local/lib64" >> /etc/ld.so.conf.d/local.conf && ldconfig && \
  cp -n /usr/local/lib/libllama*.so* /usr/lib64/ 2>/dev/null || true && ldconfig

CMD ["/bin/bash"]
